### ISSUE TITLE
Entity response from API seems to be truncated/paginated

### ISSUE THREAD

**Issue by asachs01** [sensu/grafana-sensu-go-datasource#22]
A customer reported that when they're pulling in entities via the datasource that the response seems to be truncated. In their words, "If I search for an entity beginning with 'A', I can find it, no issues. If I search for an entity beginning with 'S', I cannot find it." So it appears that API pagination may be at play here, but I'm not quite sure. More investigation is needed.

**Comment by mariusoe** [comment]
This is most likely also due to the fact that the data source has filtered the data in the browser so far. Therefore, if not all data has been retrieved (e.g. because of a limit), the result will be missing data.

Starting with version 1.1.0 the data source will support server-side filtering, which should solve this problem.

Closed by #36
