### ISSUE TITLE
release-it command doesn't work as described in readme

### ISSUE THREAD

**Issue by cwjohnston** [sensu/grafana-sensu-go-datasource#3]
When I run `release-it` as instructed in the readme, I don't see a releases directory created. Instead I've found that there are scripts defined in package.json for compiling the plugin into the `dist` directory, which can then be tarred/zipped for installation.

I believe either the readme needs to be updated with an accurate explanation of the build/release steps, or we need updates to the release-it configuration so that it does what the readme claims.

**Comment by jspaleta** [comment]
so i did get release-it to work... the language around the steps are sub-optimal.
well i got it to work on Fedora. not on the target CentOS 7 box.. it generated errors there.. probably due to needing a newer npm..which is always the case for npm things...

anyways. what we really need is an official development release... perhaps an 0.0.1 of this.. produce github release with the appropriate zip file and include instructions on how to use grafana-cli to pull that zip from github.

Once we get to a 1.0.0 release we can make a request for this to be included in the official grafana plugin directory.

**Comment by mariusoe** [comment]
@cwjohnston do you get any errors when you execute `release-it`? Basically, if you want to build a release, executing `release-it` should just do the trick.

If your working directory is not clean and you have some unstaged file, you may want to use `release-it --no-git.requireCleanWorkingDir` to ignore that, otherwise it will fail.

**Comment by cwjohnston** [comment]
I'm not sure what was going on when I originally opened this issue, but I am now able to use release-it as documented. Closing due to lack of reproduction case.
